#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="$ROOT/docs"
DEMO_DIR="$DOCS_DIR/demo"
ASSET_PLOTS_DIR="$DOCS_DIR/assets/plots"

mkdir -p "$DOCS_DIR/assets" "$DOCS_DIR/methodology" "$DEMO_DIR" "$ASSET_PLOTS_DIR"

rm -f "$DEMO_DIR"/*.html "$DEMO_DIR"/*.csv "$DEMO_DIR"/*.md
rm -rf "$DEMO_DIR/plots"
mkdir -p "$DEMO_DIR/plots"

cp "$ROOT/output/dashboard.html" "$DEMO_DIR/dashboard.html"
cp "$ROOT/output/desk_summary.md" "$DEMO_DIR/"
cp "$ROOT/output"/*.csv "$DEMO_DIR/"
cp -R "$ROOT/output/plots/." "$DEMO_DIR/plots/"

python python/build_fomc_event_study.py
python python/plot_fomc_event_study.py
if [ -f python/compare_on_the_run_to_government_curve.py ]; then
  if ! python python/compare_on_the_run_to_government_curve.py; then
    echo "Warning: government/on-the-run curve comparison could not be built" >&2
  fi
fi

for plot in \
  fomc_zero_curve_pre_post.png \
  fomc_curve_move_bp.png \
  fomc_zero_rate_surface_3d.png \
  fomc_forward_rate_surface_3d.png \
  fomc_level_slope_curvature.png \
  government_vs_on_the_run_curve_comparison.png; do
  if [ -f "$ROOT/output/plots/$plot" ]; then
    cp "$ROOT/output/plots/$plot" "$ASSET_PLOTS_DIR/$plot"
  else
    echo "Warning: plot $plot is unavailable and will not be copied to Pages assets" >&2
  fi
done

cat > "$DEMO_DIR/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Main Demo | Fixed Income Desk Quant Platform</title>
  <link rel="stylesheet" href="../assets/style.css">
</head>
<body>
  <header class="site-header">
    <nav class="nav" aria-label="Primary navigation">
      <a class="brand" href="../">Fixed Income Desk Quant Platform</a>
      <div class="nav-links">
        <a href="../">Home</a>
        <a href="./" aria-current="page">Main Demo</a>
        <a href="../event-study/">Event Study</a>
        <a href="../methodology/">Methodology</a>
        <a href="https://github.com/xiaoxu-zhao/Fixed-Income-Desk-Quant-Platform">GitHub Repository</a>
      </div>
    </nav>
  </header>

  <main>
    <section class="intro">
      <div>
        <p class="eyebrow">Generated dashboard</p>
        <h1>Main Demo</h1>
        <p class="lead">The demo page is rebuilt from the deterministic full-desk run. It publishes the static dashboard, CSV reports, plots, and desk summary used by the project.</p>
        <div class="actions">
          <a class="button" href="dashboard.html">Open Raw Dashboard</a>
          <a class="button secondary" href="../methodology/">Read Methodology</a>
        </div>
      </div>
      <div class="panel">
        <h2>Output Files</h2>
        <ul class="data-list">
          <li><a href="daily_report.csv">daily_report.csv</a></li>
          <li><a href="instrument_pv.csv">instrument_pv.csv</a></li>
          <li><a href="keyrate_dv01.csv">keyrate_dv01.csv</a></li>
          <li><a href="pnl_explain.csv">pnl_explain.csv</a></li>
          <li><a href="execution_report.csv">execution_report.csv</a></li>
          <li><a href="desk_summary.md">desk_summary.md</a></li>
        </ul>
      </div>
    </section>

    <section>
      <h2>Dashboard</h2>
      <iframe class="embed" src="dashboard.html" title="Generated fixed income desk quant dashboard"></iframe>
    </section>

    <section>
      <h2>Plot Gallery</h2>
      <div class="plot-grid">
        <figure>
          <img src="plots/yield_curves.png" alt="Yesterday and today zero curves">
          <figcaption>Yield curves</figcaption>
        </figure>
        <figure>
          <img src="plots/curve_move_bp.png" alt="Curve move in basis points by maturity">
          <figcaption>Curve move in basis points</figcaption>
        </figure>
        <figure>
          <img src="plots/keyrate_dv01.png" alt="Key-rate DV01 by pillar">
          <figcaption>Key-rate DV01</figcaption>
        </figure>
        <figure>
          <img src="plots/pnl_explain.png" alt="P and L explain chart">
          <figcaption>P&amp;L explain</figcaption>
        </figure>
        <figure>
          <img src="plots/intraday_pnl.png" alt="Intraday P and L path">
          <figcaption>Intraday P&amp;L</figcaption>
        </figure>
        <figure>
          <img src="plots/execution_report.png" alt="Execution analytics chart">
          <figcaption>Execution analytics</figcaption>
        </figure>
      </div>
    </section>
  </main>

  <footer>
    <p>Generated by scripts/run_full_demo.sh and scripts/build_pages_site.sh.</p>
  </footer>
</body>
</html>
HTML

touch "$DOCS_DIR/.nojekyll"
echo "Built GitHub Pages site under $DOCS_DIR"
